<a href="https://colab.research.google.com/github/lohith05102001/ICP3/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
v=np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]],dtype='float32')

In [11]:
v=v.reshape(3,5)
v

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]], dtype=float32)

In [12]:
print(v.shape)

(3, 5)


In [13]:
max_values = np.argmax(v, axis=1)
v[np.arange(len(v)), max_values] = 0
v

array([[ 1.,  2.,  3.,  4.,  0.],
       [ 6.,  7.,  8.,  9.,  0.],
       [11., 12., 13., 14.,  0.]], dtype=float32)

In [14]:
a=np.random.random((4,3)).astype(int)
print(a)
print(a.shape)
type(a)
print(a.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
int64


In [15]:
matrix = np.array([[3,-2],
                   [1,0]])

# Calculate eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the results
print("Eigenvalues:")
print(eigenvalues)
print("\nRight Eigenvectors (column-wise):")
print(eigenvectors)

Eigenvalues:
[2. 1.]

Right Eigenvectors (column-wise):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [16]:
m1=np.array([[0,1,2],[3,4,5]])
m1.diagonal()
np.trace(m1)

4

In [17]:
import numpy as np

def reshape(array, new_shape):


  # Check if the new shape is compatible with the original data
  if np.prod(array.shape) != np.prod(new_shape):
    print("Error: Cannot reshape array. New shape is incompatible with the original data.")
    return None

  # Reshape the array
  reshaped_array = array.reshape(new_shape)

  return reshaped_array

# Example usage:
original_array = np.array([[1,2],[3,4],[5,6]])
new_shape = (2, 3)

reshaped_array = reshape(original_array, new_shape)

if reshaped_array is not None:
  print("Original array:\n", original_array)
  print("Reshaped array:\n", reshaped_array)

Original array:
 [[1 2]
 [3 4]
 [5 6]]
Reshaped array:
 [[1 2 3]
 [4 5 6]]
